#!/bin/bash

# ansible
export ANSIBLE=2.10.7

# ansible collections
export OPENSTACK_CLOUD=1.5.1
export AMAZON_AWS=6.0.1
export IONOSCLOUDSDK_IONOSCLOUD=6.0.1
export AZURE_AZCOLLECTION=1.11.0
export COMMUNITY_GENERAL=4.8.11

# ansible playbooks
export RESOURCE_CATALOGUE=master
export DBMS_CATALOGUE=master
export DBAAS_CATALOGUE=master
export BENCHMARK_CATALOGUE=master
export MONITORING_CATALOGUE=master
export TELEGRAF_LOADER=main

# java artefacts
export EVALUATION_TASKS=master-SNAPSHOT
# benchmark-api container
export BENCHMARK_API=master
# python packages
export OPENSTACKSDK=0.61.0
export OVHSDK=1.1.0

export BAAS_PROCESSOR=2.0.0+master

